# 新版 docker-compose 不需要指定版本
# version: '3.9'

# 潘的程序员黑市

services:
  market-server:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: 'market-server'
    command:
      - -- debug=false
      - -- spring.datasource.url=jdbc:mysql://market-mysql:3306/market_plus_db?characterEncoding=utf-8
      - -- spring.datasource.username=root
      - -- spring.datasource.password=MySQL123@tecwds
      - -- spring.mail.host=smtp.163.com
      - -- spring.mail.username=${邮箱用户名}
      - -- spring.mail.password=${邮箱授权码}
      - -- sa-token.jwt-secret-key=${生成jwt的密钥}
      - -- market.secret-key=${密码加密密钥}
      # 默认端口为 39150
      - -- server.port=39150
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      # 需要开放邮箱端口
      - "25:25"
      - "465:465"
      - '39150:39150'
    networks:
      market-net:
    logging:
      driver: 'json-file'
      options:
        max-size: '1G'
    healthcheck:
      test: "curl --fail --silent localhost:39150/api/healthy | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      market-mysql:
        condition: service_healthy

  market-mysql:
    image: 'mysql:5.7'
    container_name: 'market-mysql'
    restart: unless-stopped
    command:
      # 设置字符集
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    volumes:
      - 'market-mysql-d:/var/lib/mysql'
      # 用于初始化数据库
      - '../sql:/docker-entrypoint-initdb.d/'
    environment:
      - MYSQL_ROOT_PASSWORD=MySQL123@tecwds
      - TZ=Asia/Shanghai
    networks:
      market-net:
    ports:
      - '6666:3306'
    tty: true
    stdin_open: true
    logging:
      driver: 'json-file'
      options:
        max-size: '1G'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  market-net:
    name: 'market-net'
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.19.8.0/24
          gateway: 10.19.8.1

volumes:
  market-mysql-d:
